### ISSUE TITLE
Get AWS accounts for production use of MTurk

### ISSUE THREAD

**Issue by hschilling** [nasa-petal/data-collection-and-prep#25]
### Summary of Issue

Work with NASA Goddard's cloud group to get NASA AWS accounts

**Comment by bruffridge** [comment]
@hschilling current status?

**Comment by bruffridge** [comment]
Does Goddard have a list of AWS services we'd be allowed to use? Shruti is looking into AWS options for running her ML code and wanted to know if there are limitations in terms of which services we'll have access to.

**Comment by hschilling** [comment]
I have my AWS account but I can't get to MTurk through it. I emailed Goddard and also the MTurk product manager. No replies from either. 

Pratima has not been fully approved in NAMS.

**Comment by hschilling** [comment]
AWS keys from Goddard's Mission Cloud Platform work
