### ISSUE TITLE
Look into a json diff solution

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/data-collection-and-prep#94]
To attach to PRs for updating golden.json so the reviewer can see what the changes are.

**Comment by bruffridge** [comment]
https://stackoverflow.com/questions/31930041/using-jq-or-alternative-command-line-tools-to-compare-json-files
https://github.com/josephburnett/jd
https://github.com/jlevy/pdiffjson

**Comment by bruffridge** [comment]
@rebeccalipton A diff tool visualizes the changes made to a file. Typically the original file is shown on the left, and the new version on the right. Here's an example of a diff generated by GitHub. https://github.com/nasa-petal/PeTaL-labeller/pull/85/files Unfortunately GitHub's built-in diff tool doesn't work for large files. We need to generate diffs for this file - https://github.com/nasa-petal/data-collection-and-prep/blob/main/golden.json. The diff report should ideally be exportable to pdf, or html so it can be attached to GitHub pull requests.

**Comment by rebeccalipton** [comment]
I found three options to create a diff file for JSON comparisons. These all render output that can be attached to a commit, and therefore GitHub pull requests as well.

https://pypi.org/project/json-diff/  
"Compares two JSON files and generates a new JSON file with the result."

https://github.com/trailofbits/graphtage
Compares two file types (including JSON) and generates a new file with the output. Can specify output type, such as html.

https://github.com/j-tester/json-diff-cli
Finds the diff between two JSON URLs. Prints the diff to console or outputs as csv file.

**Comment by hschilling** [comment]
Thanks! I will check them out.

**Comment by pjuangph** [comment]
I like the generated JSON file as a result approach. This should work for all cases; however, sometimes a JSON can be represented as a CSV file, I think golden json can be a csv so that's a better option.

**Comment by bruffridge** [comment]
Looks like graphtage is the most promising out of the three.

**Comment by rebeccalipton** [comment]
After evaluating multiple libraries and packages to generate a diff file for the golden.json, three options to complete this task are detailed in an earlier comment. Upon further inspection by the PeTaL team, the [graphtage](https://github.com/trailofbits/graphtage) library seems like a top contender since it can render the diff as an HTML file, which can then be committed with Git. The graphtage library has the most similarity to the traditional diff files that GitHub renders.
