### ISSUE TITLE
Create a pipeline for training data ingestion, merging, cleaning, validation and transformation

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/data-collection-and-prep#97]

**Comment by bruffridge** [comment]
https://github.com/nasa-petal/data-collection-and-prep/issues/93#issuecomment-883660235

**Comment by bruffridge** [comment]
subtasks/related to: #93, #94.

**Comment by bruffridge** [comment]
dagshub.com may be useful. or DVC

**Comment by bruffridge** [comment]
https://greatexpectations.io/ - framework that can help with automation of data quality validation

- [ ] Define the golden.json fields that are required for our ML model to function properly. @elkong

**Comment by elkong** [comment]
_(cross-posted in the Discord)_

I mentioned I'd have some ideas for `golden.json` quality checks. Partly based on what problems have come up in the past, here are a few I propose I'd like to see. Besides checks on datatype (e.g., "is this a string?", "is this an array of numbers?"):

```
In general:
- Are text fields free of any non-ASCII characters?
- Are arrays free of duplicates?

DOI
- Is it well-formed?
- Does it resolve?

Level1, Level2, Level3 labels
- Can each label be found in the taxonomy file?
- Conditional on isBiomimicry being true, is level1 non-empty?
- Are these not strings, but lists of strings?

Title
- Is it non-empty?

Abstract
- Is it non-empty?

URL
- Does it resolve?

fullDocLink
- Conditional on isOpenAccess being true, does it resolve?
```

And if I can ask for the moon on a silver platter:
```
venue_mag and venue
- Does each venue have a distinct name? (e.g., we don't have both "PNAS" and "Proceedings of the National Academy of Sciences of the United States of America" in the dataset)
```
(that one's actually not too important, but it might help)

Notes:
- It would be nice for metadata (venue, authors, references, and MAG fields of study) to be non-empty, but for the sake of not throwing out too much good data, I'll only require that the text fields (title and abstract) are non-empty.
- Sometimes I find labels in `golden.json` that cannot be found in the taxonomy file, and vice versa. Currently, the labels in `golden.json` which are not in the taxonomy file are:
```
['sense_chemicals',
 'manage_environmental_disturbances',
 'cooperate_within/between_species',
 'move_through/on_solids',
 'manage_environmental_disturbances_in_a_community',
 'send_chemical_signals',
 'move_through/on_liquids',
 'sense_send_or_process_information',
 'compete_within/between_species',
 'sense_disease',
 'move_through_gases',
 'store_soilds']
```
And the labels in `taxonomy.txt` which are not in the golden dataset are
```
['send_chemical_signals_',
 'sense_disease_in_a_living_system',
 'self-replicate',
 'chemically_assemble_inorganic_compounds',
 'sense_chemicals_',
 'send_tactile_signals',
 'compete_within_or_between_species',
 'manage_environmental_disturbance_in_a_community',
 'store_solids',
 'cooperate_within_or_between_species',
 'sense,_send,_or_process_information']
```
I know the PeTaL taxonomy's gone through some overhauling, so I hope I don't have an outdated `taxonomy.txt` file yet.

What are your thoughts on how feasible it is to implement these checks, and how important they are? Am I missing anything obvious? All of this is open to revision.

**Comment by dsmith111** [comment]
Issue resolved with new repository:
https://github.com/nasa-petal/petal-labeler-data-pipeline
